apiVersion: v1
kind: Secret
metadata:
    name: app-secrets
    namespace: reminder-bot
type: Opaque
stringData:
    BOT_TOKEN: ENC[AES256_GCM,data:isM58Z3RQKASla3kwndVsHbaP4KzY2Lz9Yqv10YFyIjumkcpO/74kzO6YOPjkA==,iv:X9oosS1W4hGkuaPY4QroUYvdCyIEIEGB8JhU95Si/2Y=,tag:EwDtZDd1p2HWibAUCsQ/YQ==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:2c0bN1WAWyA=,iv:wQLJ4MTPBLDdU1eUC2MpzjhAaJNyd9EO+NlBy4JnFPE=,tag:HN+bDVe7PHX5/Ytwn9QGzA==,type:str]
    DB_URL: ENC[AES256_GCM,data:+D3gfTqEiIAZsP3tVvqqbDDqAMRA9mwfshN4/zUzoqx1uw+dpQElH23F7qXE3sOhdjHKBZKktksPld2WUJkwg+vHUEu3ljHs3fWVoNFdTQ==,iv:wW09LfxgA/md/vQgeS6lnyAeMXrfYrIknqUy+ahIlTA=,tag:6meHubd2s9ESrWraQoiGwA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkcDAwelM2dWlNSzhKWVNB
            dmlQZ25WWW1lUzF4N0w2L09TYk10cUQyK2pVCit5bGV2aWRlSVc5d0tuVFlDWXFM
            V3FlaFRGTVJvVVNGTzRvOWVpT0VDTWMKLS0tIEMwa3VKQmxNZlVjdVNqZ2FLMjlV
            RXNZVGFYY2ZDOFFGcTBtQVZxcUdoc0EKUWZmVE58mbByGu2XxwnNE4/WwKYqbhCa
            Ay99TsfxodTCk+CLXpbHc1eHgw7o+x0bz0WAZzqENNn2rGGroioMlg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sh4gkd6vtq97pl0fwc43mfq5sh5f0a92t2zm8ktk5h3fln0cs43qfpgm3t
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArRkRUQzYrM3g2QnlWUmVI
            Vm5nRGJlUTJOa2hUUk41TUEwd09XY3gxZnl3Ck5DOWxRaTROV1F3N010WXYyRExN
            SlU4STM4NGkyM2w0REpXdENJbFNnUmcKLS0tIFVtck1YQkhuR2Q1ZVhtVWUzSWwx
            VDJhRnNtMDFadXNrTmMrOTU5SlRTblUKp54tzIR9nzcfUX5VpFxzTREviN5OfUwM
            y93yZYxoWDltNiZA/7z1acyT7YM2SPzGUNfWLJ6cK5rMtjVqiaOg5A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nrfs0cgysk6tpxq04l2yzhgm9edaklqsfmfdfzftrq8phx5hrgqq3ax5qq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-18T20:33:04Z"
    mac: ENC[AES256_GCM,data:hdT01Rmq7BwW0eqpwO+8juuT72M/nSoFT0QuWfZJktIraiQ+o/7B+B/0lGe5n8fO08RlE9URKVLXs619So157q3Do8lJwQXvxvHRiXcrybcPQTVBn1LJEdhuuP39ujRdkdq72pp6T8fH9IqIsVyL/Iis8HdQsTV+5LksbQzLYko=,iv:2em/Q7XBCgamJptt92XLyOUkMMFhWxEEO1vf28Glako=,tag:HKAZIKLV/ezs7Wz8L9zGbg==,type:str]
    version: 3.13.1
