apiVersion: v1
kind: Secret
metadata:
    name: ghcr-secret
    namespace: reminder-bot
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:uryO+C9BylV+6FRiyXMbBuNAVSw3rKAGh4lORyb7wHSBsMOkHZKFtHLzTafLtb+1ySTZU43faMSl4kvMibUMgdbj2hNEnZZcivSrFS5TEuq72beH3JRj4v4SPpgBPxJFT34bT2uwSL4geJ97,iv:Ga0eahd761mfxqwosjjm+lFzOoo34XMSmSDTKWRtR6Y=,tag:haIkQPeq4caygUQRMPi+OQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDb1krajRLVVVtL2lsSFFv
            NkNBdDk5VWdSelVoS1p4clAwMzBDbCtBbXlvClJDN3FtMEFUODU3dFNSdWlOUzV6
            ZVd6dzdVU1ZaWVFMSHh6M2lwcjRYelkKLS0tIDl6aHZCTThnY0o4ZVZYSXhES0xw
            OXpjUmpHL21DeSswL0pKSmpGalJNU1kK5xzoJhuuLoA0Uw/8eU7PxJX7jg6t1+kV
            KUe7cnNBlqyStyE1Hn5axd+sks4hcE01XgZLCyEVqUzlHZ/duyFHrg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sh4gkd6vtq97pl0fwc43mfq5sh5f0a92t2zm8ktk5h3fln0cs43qfpgm3t
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpYjZJQ0M5dUZjSXlIc3JN
            R0VqYUVTVHlVY0kxNklZWFlrSTluUUhiZDNJCmp6eCtmMExaTXRSUWdxaHFxN2xG
            dmxSQXVYdnpZSnhpS0JXVFJQblBCRncKLS0tIEpwdzUveURWNy9lb21SbFY0Z1FT
            Y3R1OEVVWnJYMXBXNnFQYVZqaEZFd0EKXVSqar4g5eI9ngAZvQaEP50WfCbp4eu+
            Iqi+mYcQ/a7o6d1QYcPfQc8vQuag14xx37a6014qaq+YabT7Jx4EOA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nrfs0cgysk6tpxq04l2yzhgm9edaklqsfmfdfzftrq8phx5hrgqq3ax5qq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-18T17:05:49Z"
    mac: ENC[AES256_GCM,data:dBkQ8SDL68fomrBCCAl2n4ofcnZm+hqNhkMKkhbFdGyOfJ67mEBz9wcY9NBFDVaYgNukc1Wrsb4sAVxnnLQ9dQRgH1vLNQMh52odXWvDkB1IDNxGwKu/Ph2eOCJKPzucH6NJ0ksgHlCZbOdh9iSajqys8W/sXR3LLqeLwVJIuws=,iv:TjTUmtizDa6KTJJn2c367F4L+YKDSyjm2rFYKzWWu6g=,tag:urT6mNiDBCWrL1M0kKG7SQ==,type:str]
    version: 3.13.1
