apiVersion: v1
kind: Secret
metadata:
    name: ghcr-secret
    namespace: reminder-bot
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:uryO+C9BylV+6FRiyXMbBuNAVSw3rKAGh4lORyb7wHSBsMOkHZKFtHLzTafLtb+1ySTZU43faMSl4kvMibUMgdbj2hNEnZZcivSrFS5TEuq72beH3JRj4v4SPpgBPxJFT34bT2uwSL4geJ97,iv:Ga0eahd761mfxqwosjjm+lFzOoo34XMSmSDTKWRtR6Y=,tag:haIkQPeq4caygUQRMPi+OQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTQkY5SlRlT2d3T3ZlMHNK
            VnFOR2RxVGxTUkZ2RlMxdWNSYVlmSUNHdmxBCjdoUXZvN1BIZm1YRDd1c0xWdy9J
            YXJicnhoZ0NrM3dzSWdJU090cEVmbDgKLS0tICtONTZMazMzNW53bVRYL1c2aXR6
            NW55dnN3ckNWTjgwOCs1ZDFVWWdjK3MKVL6kJOcTiwtK6vqnQD+zYgRn7WSnSYcO
            DQ/BtDlmhk+rQtk2wrCGHLUqPXEGxKSWVXNQqJeAIOeySv+2qhFRKQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sh4gkd6vtq97pl0fwc43mfq5sh5f0a92t2zm8ktk5h3fln0cs43qfpgm3t
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-18T17:05:49Z"
    mac: ENC[AES256_GCM,data:dBkQ8SDL68fomrBCCAl2n4ofcnZm+hqNhkMKkhbFdGyOfJ67mEBz9wcY9NBFDVaYgNukc1Wrsb4sAVxnnLQ9dQRgH1vLNQMh52odXWvDkB1IDNxGwKu/Ph2eOCJKPzucH6NJ0ksgHlCZbOdh9iSajqys8W/sXR3LLqeLwVJIuws=,iv:TjTUmtizDa6KTJJn2c367F4L+YKDSyjm2rFYKzWWu6g=,tag:urT6mNiDBCWrL1M0kKG7SQ==,type:str]
    version: 3.13.1
