apiVersion: v1
kind: Secret
metadata:
    name: ghcr-secret
    namespace: reminder-bot
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:M9j/wq3BvlDy08eEwy0BTLTRcMZpel7JXW0psPJgwmUDYlCEBUVbO+YTx3aSv4MVUl3zDosfKZceXkcwPTRt0dmz/qQG7sEvl0NL0at+/rRIV3R+z6d9d6uARq6HUgbuU5wwUuyEy/y5bj4fAkxFFlaYcJcuoogA8hS+ZZ3UmEZozFUPkCBgvF+ajbDxZsaVGMP6R3aMdGgOZp14ZZO/n4yWyF0FeEH0JwzjcA==,iv:v0lWR+MxMzrb1ypOR55kTnXSi98dn4hi6sEx83mHdU4=,tag:6pNEVZqLWKLN+q2xD6qxUQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDb1krajRLVVVtL2lsSFFv
            NkNBdDk5VWdSelVoS1p4clAwMzBDbCtBbXlvClJDN3FtMEFUODU3dFNSdWlOUzV6
            ZVd6dzdVU1ZaWVFMSHh6M2lwcjRYelkKLS0tIDl6aHZCTThnY0o4ZVZYSXhES0xw
            OXpjUmpHL21DeSswL0pKSmpGalJNU1kK5xzoJhuuLoA0Uw/8eU7PxJX7jg6t1+kV
            KUe7cnNBlqyStyE1Hn5axd+sks4hcE01XgZLCyEVqUzlHZ/duyFHrg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sh4gkd6vtq97pl0fwc43mfq5sh5f0a92t2zm8ktk5h3fln0cs43qfpgm3t
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpYjZJQ0M5dUZjSXlIc3JN
            R0VqYUVTVHlVY0kxNklZWFlrSTluUUhiZDNJCmp6eCtmMExaTXRSUWdxaHFxN2xG
            dmxSQXVYdnpZSnhpS0JXVFJQblBCRncKLS0tIEpwdzUveURWNy9lb21SbFY0Z1FT
            Y3R1OEVVWnJYMXBXNnFQYVZqaEZFd0EKXVSqar4g5eI9ngAZvQaEP50WfCbp4eu+
            Iqi+mYcQ/a7o6d1QYcPfQc8vQuag14xx37a6014qaq+YabT7Jx4EOA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nrfs0cgysk6tpxq04l2yzhgm9edaklqsfmfdfzftrq8phx5hrgqq3ax5qq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-18T20:38:31Z"
    mac: ENC[AES256_GCM,data:StFEq3ZpZv3WvkNiaK5qdGwvoD36IJuP9NlghfhG/+BnG/ImkH2lQNi4ByITbx1ZI3rWBpI1HRjS/VZzz9eT1mIuSVr2qI1xzlqptutgDVBEBrqe+84QlI+FVl88/qRVMeTPSZnpiNyN9i7a3lTboG7d2/7fdCK7G6i4MHlnBHc=,iv:xPVYnaZ6ZBy2LWMOlVEgIXzi9deLSDpU8ZpW6p0EzJI=,tag:kp7UhXoy+qTGBPuTEfYYqg==,type:str]
    version: 3.13.1
